# Generated by Django 2.1.2 on 2018-10-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('nationality', models.CharField(blank=True, max_length=512, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=512, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=512, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=512, null=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employee.Employee')),
            ],
        ),
    ]
